version: '3.5'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
      target: development
    container_name: fibonacci-sequence-service-dev
    env_file:
      - .env.dev
    command: npm run start:dev
    ports:
      - 8000:8000
    restart: 'always'

