##########################
# BUILD FOR DEVELOPMENT
##########################
FROM node:16.13.0-alpine As development

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./

RUN yarn --only=development

COPY . .

RUN npm run build

##########################
# COPY ALL FILES AND RUN
##########################
FROM node:16.13.0-alpine as run

ENV NODE_ENV=dev

WORKDIR /usr/src/app

COPY .env.dev ./

COPY --from=development /usr/src/app/node_modules ./node_modules
COPY --from=development /usr/src/app/package.json ./package.json
COPY --from=development /usr/src/app/tsconfig.json ./tsconfig.json
COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]